# Generated by Django 4.1 on 2022-08-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0002_remove_room_name_room_connected_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_group_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
