# Generated by Django 4.1 on 2022-08-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0004_alter_room_connected_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
